/* Copyright © 2021 Softel vdm, Inc. - https://yetawf.com/Documentation/YetaWF/Sites#License */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YetaWF.Core.Controllers;
using YetaWF.Core.DataProvider;
using YetaWF.Core.Models;
using YetaWF.Core.Models.Attributes;
using YetaWF.Core.Modules;
using YetaWF.Core.Site;
using YetaWF.Modules.Sites.Modules;
using YetaWF.Core.Components;
#if MVC6
using Microsoft.AspNetCore.Mvc;
#else
using System.Web.Mvc;
#endif

namespace YetaWF.Modules.Sites.Controllers {

    public class SitesBrowseModuleController : ControllerImpl<YetaWF.Modules.Sites.Modules.SitesBrowseModule> {

        public class BrowseItem {

            [Caption("Actions"), Description("The available actions")]
            [UIHint("ActionIcons"), ReadOnly]
            public MenuList Commands { get; set; }

            public async Task<MenuList> __GetCommandsAsync() {
                MenuList actions = new MenuList() { RenderMode = ModuleAction.RenderModeEnum.IconsOnly };

                actions.New(Module.GetAction_SiteDisplay(SiteData), ModuleAction.ActionLocationEnum.GridLinks);
                actions.New(await SiteEditModule.GetModuleActionAsync("EditSite", null, SiteDomain), ModuleAction.ActionLocationEnum.GridLinks);
                actions.New(ConfirmModule.GetAction_Remove(null, SiteData), ModuleAction.ActionLocationEnum.GridLinks);
                return actions;
            }

            [Caption("Site Domain"), Description("The domain name of the site")]
            [UIHint("String"), ReadOnly]
            public string SiteDomain { get; set; }

            [Caption("Default Site"), Description("Shows whether the site is the default site for this instance of YetaWF - the default site cannot be removed")]
            [UIHint("Boolean"), ReadOnly]
            public bool IsDefaultSite { get; set; }

            [Caption("Site Name"), Description("The name associated with your site, usually your company name or your name")]
            [UIHint("String"), ReadOnly]
            public string SiteName { get; set; }

            [Caption("Site Id"), Description("The id associated with your site, generated by YetaWF when the site is created")]
            [UIHint("IntValue"), ReadOnly]
            public int Identity { get; set; }

            private SitesBrowseModule Module { get; set; }
            private ModuleDefinition SiteEditModule { get; set; }
            private SiteDefinition SiteData { get; set; }
            private ConfirmRemovalModule ConfirmModule { get; set; }

            public BrowseItem(SitesBrowseModule module, ModuleDefinition siteEditModule, ConfirmRemovalModule confirmModule, SiteDefinition site) {
                Module = module;
                SiteData = site;
                SiteEditModule = siteEditModule;
                ConfirmModule = confirmModule;
                ObjectSupport.CopyData(site, this, ForceReadOnlyFromCopy: true);
                Identity = site.Identity;
            }
        }

        public class BrowseModel {
            [UIHint("Grid"), ReadOnly]
            public GridDefinition GridDef { get; set; }
        }
        private GridDefinition GetGridModel() {
            return new GridDefinition {
                ModuleGuid = Module.ModuleGuid,
                SettingsModuleGuid = Module.PermanentGuid,
                RecordType = typeof(BrowseItem),
                AjaxUrl = GetActionUrl(nameof(SitesBrowse_GridData)),
                DirectDataAsync = async (int skip, int take, List<DataProviderSortInfo> sort, List<DataProviderFilterInfo> filters) => {
                    ModuleDefinition siteEditModule = await ModuleDefinition.LoadAsync(new Guid("522296A0-B03B-49b7-B849-AB4149466E0D"));
                    ConfirmRemovalModule confirmModule = new ConfirmRemovalModule();

                    DataProviderGetRecords<SiteDefinition> info = await SiteDefinition.GetSitesAsync(skip, take, sort, filters);
                    return new DataSourceResult {
                        Data = (from s in info.Data select new BrowseItem(Module, siteEditModule, confirmModule, s)).ToList<object>(),
                        Total = info.Total
                    };
                },
            };
        }
        [AllowGet]
        public ActionResult SitesBrowse() {
            BrowseModel model = new BrowseModel {
                GridDef = GetGridModel()
            };
            return View(model);
        }

        [AllowPost]
        [ConditionalAntiForgeryToken]
        public async Task<ActionResult> SitesBrowse_GridData(GridPartialViewData gridPVData) {
            return await GridPartialViewAsync(GetGridModel(), gridPVData);
        }
    }
}